[project]
name = "new-certificazione-770"
version = "0.2.0"
description = "Application for Certificazioni 770 for company Herbalife S.p.A. to create output file for INPS fiscal application"
authors = [
    {name = "Dottorlink", email = "dottorlink@gmail.com"},
]
dependencies = [
    "tkcalendar",
    "pandas",
    "sv_ttk",
    "darkdetect",
    "sqlmodel",
    "openpyxl",
    "pydantic",
    "pyinstaller>=6.10.0",
    "git-changelog>=2.5.2",
    "pywinstyles>=1.8",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["hatchling", "hatch-pyinstaller",]
build-backend = "hatchling.build"


[tool.cxfreeze]
executables = [
    {script = "./src/new_certificazione_770/main.py.py", base = "gui"}
]

[tool.cxfreeze.build_exe]
excludes = ["tkinter", "unittest"]
zip_include_packages = ["tkcalendar", "babel.numbers", "openpyxl"]
path = "./src/new_certificazione_770/"
optimize = 2

[tool.pdm]
distribution = true
